# [Advent of Code 2020](https://adventofcode.com/2020)

NB: Installer jupyter lab i venv, og start så med `venv/bin/jupyter lab`

# --- Day 1: Report Repair ---

In [1]:
import numpy as np
f = np.loadtxt('data/advent_of_code_2020_day_1.txt')
f

array([1837., 1585., 1894., 1715., 1947., 1603., 1746., 1911., 1939.,
       1791., 1800., 1479., 1138., 1810., 1931., 1833., 1470., 1882.,
       1725., 1496., 1890., 1862., 1990., 1958., 1997., 1844., 1524.,
        541., 2001., 1591., 1687., 1941., 1940., 1561., 1813., 1654.,
       1500., 1575., 1826., 2006.,  679., 1660., 1679., 1631., 2008.,
        575., 1583., 1883., 1904., 1436., 1650., 1532., 1907., 1803.,
       1693., 1700.,  359., 1516., 1625., 1908., 1994., 1910., 1644.,
       1706., 1781., 1639., 1662., 1712., 1796., 1915., 1550., 1721.,
       1697., 1917., 1665., 1646., 1968., 1881., 1893., 1468., 1678.,
       1774.,  285., 1754., 1856., 1677., 1823., 1802., 1681., 1587.,
       1767., 1711., 1900., 1983., 1787., 1996., 1726., 1982., 1971.,
       1553., 1542., 1863., 2002., 1831., 1891., 1555., 2000., 1847.,
       1783., 1873., 1761., 1742., 1534., 1993., 1898., 1973., 1974.,
       1597., 1540., 1581., 1864., 1452., 1637., 1649., 1886., 1965.,
       1460., 1664.,

In [2]:
for expense in f:
    tmp_array = expense + f
    if np.isin(2020, tmp_array) == True:
        n1 = expense
        n2 = f[np.where(tmp_array == 2020)]
        break # Skip the second tmp_array,where n1 and n2 are reverse
print ('Part 1: ', int(n1*n2))

Part 1:  800139


In [3]:
finished=False
for expense2 in f:
    sum2 = expense2 + f
    for expense3 in f:
        sum3 = sum2 + expense3
        if np.isin(2020, sum3) == True:
            expense1 = f[np.where(sum3 == 2020)]
            # Save variables here, not so easy to also break out of outer loop
            n1=expense1
            n2=expense2
            n3=expense3
            break
print ('Part 2: ', int(n1*n2*n3))

Part 2:  59885340


# --- Day 2: Password Philosophy ---

In [4]:
import re
with open("data/advent_of_code_2020_day_2.txt", "r") as fp:
    data = fp.readlines()

p1 = p2 = 0
for line in data:
    m = re.match(r"^([0-9]+)-([0-9]+) ([a-z]): ([a-z]+)\n$", line)
    n1 = int(m.group(1))
    n2 = int(m.group(2))
    w = m.group(3)
    pwd = m.group(4)   
    if n1 <= pwd.count(w) <= n2:
        p1 += 1
    a = pwd[n1-1] == w
    b = pwd[n2-1] == w
    if (a and not b) or (not a and b): # XOR
        p2 += 1
p1, p2

(666, 670)

# --- Day 3: Toboggan Trajectory ---
First create a comma-separated file from the input file where '.' is replaced with 0 and '#'  is replaced with 1:

```
sed 's/\./0/g' advent_of_code_2020_day_3.txt > aoc_3.txt
sed -i 's/#/1/g' aoc_3.txt
sed -i 's/\([01]\)/\1,/g' aoc_3.txt
sed -i 's/,$//' aoc_3.txt
```

In [5]:
import numpy as np
slope = np.loadtxt('data/aoc_3.txt', delimiter=',')
print(np.shape(slope))
slope

(323, 31)


array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 1., 1., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.]])

In [6]:
r = c = 0  # start position for row and column
tree = 0
rmax, cmax = np.shape(slope)
while r < rmax:
    if c > cmax-1:  # since np.shape gives length
        c -= cmax
    if slope[r][c] == 1:
        tree += 1
    c += 3  # right 3
    r += 1  # down 1
print('Part 1: ', tree)

Part 1:  280


In [7]:
# Part Two
def get_trees(slope,right,down):
    r = c = 0  # start position for row and column
    tree = 0
    rmax, cmax = np.shape(slope)
    while r < rmax:
        if c > cmax-1:  # since np.shape gives length
            c -= cmax
        if slope[r][c] == 1:
            tree += 1
        c += right
        r += down
    return tree
print('Part 2:')
get_trees(slope, 1, 1) * get_trees(slope, 3, 1) * get_trees(slope, 5, 1) *\
get_trees(slope, 7, 1) * get_trees(slope, 1, 2)

Part 2:


4355551200

# --- Day 4: Passport Processing ---
(bad parsing of input data..)

In [8]:
passport_list = []
passport_data = ""
with open('data/advent_of_code_2020_day_4.txt') as f:
    for line in f:
        if line == '\n': # Ok?
            passport_list.append(passport_data)
            passport_data =""
            continue
        line=line.replace('\n',',')
        passport_data += line.replace(" ", ",")
    passport_list.append(passport_data) # Also append last passport
passport_list[0]

'byr:1983,iyr:2017,pid:796082981,cid:129,eyr:2030,ecl:oth,hgt:182cm,'

In [9]:
# Convert to a list of dictionaries
passport_list_dicts = []
for x in passport_list:
    d = {}
    x = x[:-1] # Remove last comma
    passport_fields = x.split(',')
    for p in passport_fields:
        field = p.split(':')
        #print(field)
        d[field[0]] = field[1]
    passport_list_dicts.append(d)
passport_list_dicts[0]

{'byr': '1983',
 'iyr': '2017',
 'pid': '796082981',
 'cid': '129',
 'eyr': '2030',
 'ecl': 'oth',
 'hgt': '182cm'}

In [10]:
def validate_passport(passport_dict):
    """Return 1 if valid passport, else 0"""
    valid=0
    required_fields = ("byr", "iyr", "eyr", "hgt", "hcl", "ecl", "pid")
    def valid_byr(x):
        if len(x) == 4:
            return (int(x) >= 1920) and (int(x) <= 2002)
        else:
            return False
    def valid_iyr(x):
        if len(x) == 4:
            return (int(x) >= 2010) and (int(x) <= 2020)
        else:
            return False
    def valid_eyr(x):
        if len(x) == 4:
            return (int(x) >= 2020) and (int(x) <= 2030)
        else:
            return False
    def valid_hgt(x):
        h = x[:-2]
        if x[-2:] not in ('cm', 'in'):
            return False
        if x[-2:]=='cm':
            return (int(h)>=150) and (int(h)<=193)
        else:
            return (int(h)>=59) and (int(h)<=76)
    def valid_hcl(x):
        if x.startswith('#') and len(x)==7:
            for i in x[1:]:
                if i not in("a","b", "c", "d", "e", "f", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"):
                    return False
            return True
        else:
            return False
    def valid_ecl(x):
        if x in ("amb", "blu", "brn", "gry", "grn", "hzl", "oth"):
            return True
        else:
            return False
    def valid_pid(x):
        if len(x) == 9 and x.isdigit():
            return True
        else:
            return False   
    p = passport_dict    
    if all (k in passport_dict for k in required_fields):
        if valid_byr(p['byr']) and valid_iyr(p['iyr']) \
        and valid_eyr(p['eyr']) and valid_hgt(p['hgt']) \
        and valid_hcl(p['hcl']) and valid_ecl(p['ecl']) \
        and valid_pid(p['pid']):
            valid=1
    return valid

In [11]:
# Check all passports
n_valid_passports = 0
for passport in passport_list_dicts:
    #print(passport)
    if validate_passport(passport):
        n_valid_passports +=1       
print("Number of valid passports: {}".format(n_valid_passports))

Number of valid passports: 188


# --- Day 5: Binary Boarding ---

In [12]:
with open("data/advent_of_code_2020_day_5.txt", "r") as f:
    data = f.read().split('\n')[:-1]
#data

In [13]:
def get_seat_id(seat):
    row = (0, 128)
    col = (0, 8)
    for s in seat:
        if s == 'F':
            row = (row[0], row[0]+(row[1]-row[0])/2)
        elif s == 'B':
            row = (row[0]+(row[1]-row[0])/2, row[1])
        elif s == 'L':
            col = (col[0], col[0]+(col[1]-col[0])/2)
        elif s == 'R':
            col = (col[0]+(col[1]-col[0])/2, col[1])
    return row[0]*8 + col[0]    

# get_seat_id('BBFFBBFRLL')
seat_ids = [get_seat_id(seat) for seat in data]
print('Part 1: ', max(seat_ids))

Part 1:  822.0


In [14]:
# Find where the difference between seat ids is different from 1
sorted_ids = sorted(seat_ids)
diff = sorted_ids-np.roll(sorted_ids, 1)
idx = np.where(diff != 1)
idx
# Elements that roll beyond the last position are re-introduced at the first. 
# Hence, take the second index (see np.roll)

(array([  0, 692]),)

In [15]:
sorted_ids[691:693]

[704.0, 706.0]

Part 2: The missing seat ID thus is 705

# --- Day 6: Custom Customs ---

In [16]:
with open('data/advent_of_code_2020_day_6.txt') as f:
    answers = f.read().strip().split('\n\n')
p1 = p2 = 0
for a in answers:                            # 'mhqunico\nmchio\nhciwosm'
    n_answers = len(a.split('\n'))           # 3
    all_answers = a.replace('\n','')         # 'mhqunicomchiohciwosm'
    unique_answers = set(list(all_answers))  # {'c','h','i','m','n','o','q','s','u','w'}
    p1 += len(unique_answers)
    for i in unique_answers:
        if all_answers.count(i) == n_answers:
            p2+=1
p1, p2

(6947, 3398)

# --- Day 7: Handy Haversacks ---

In [17]:
import networkx as nx
import re

def string_to_graph(G, s):
    """Note: G should be a directed graph"""
    regex = re.compile('[^a-zA-Z ]')
    s = re.sub('bags|bag', '', s)  # greedy!
    main_node = s.split('contain')[0].strip()
    leaf_nodes = s.split('contain')[1].split(',')
    if "no other" in leaf_nodes[0]:
        G.add_node(main_node)
    else:
        for node in leaf_nodes:
            n=int(re.findall(r'\d+', node)[0])
            leaf_node = regex.sub('', node).strip()
            G.add_edge(main_node, leaf_node, n_bags=n)
            
def get_root_nodes(list_bag_info):
    root_nodes = []
    for s in list_bag_info:
        s = re.sub('bags|bag', '', s)
        main_node = s.split('contain')[0].strip()
        root_nodes.append(main_node)
    return root_nodes

In [18]:
with open('data/advent_of_code_2020_day_7.txt') as f:
    bag_info = f.read().split('\n')[:-1]
#bag_info

In [19]:
G = nx.DiGraph()
for b in bag_info:
    string_to_graph(G, b)

In [20]:
root_nodes = get_root_nodes(bag_info)
root_nodes.remove('shiny gold')
#root_nodes

In [21]:
p1 = 0
for bag in root_nodes:
    if nx.has_path(G, bag, 'shiny gold'):
        p1 +=1
print('Part 1: ', p1)

Part 1:  261


Oppgaven er å telle antall bager som shiny gold må inneholde.
Starter med å gi inn rotnoden og en counter (starter på 0)
Dersom vi er på en bladnode skal funksjonen returnere 1.
For hvert barn henter man ut en multiplier som tilsvarer antall bager parenten består av.
Summen til barnet er da denne multiplieren ganger et rekursivt funksjonskall.
Dette legges så til totalsummen.
Man må også ta med antall bager parenten består av. Dette skal bare gjøres dersom det ikke er en bladnode (for å unngå dobbelttelling)

In [22]:
def calc_bags(G, parent, count):
    if G.out_degree(parent) == 0: # Leaf node
        return 1
    for child in dict(G[parent]):
        n_child = len(dict(G[parent]))
        multiplier = G.edges[parent, child]['n_bags']
        child_sum = multiplier*calc_bags(G, child, 0)
        count += child_sum
        if G.out_degree(child) != 0: # Not leaf node
            count+=multiplier
    return count
print('Part 2: ', calc_bags(G, 'shiny gold', 0))

Part 2:  3765


# --- Day 8: Handheld Halting ---

In [23]:
import re
with open("data/advent_of_code_2020_day_8.txt", "r") as fp:
    data = fp.readlines()
print(len(data))
#data

601


In [24]:
accumulator = 0
operation = []
number = []
for i, line in enumerate(data):
    m = re.match(r"(.*) (.*)\n$", line)
    operation.append(str(m.group(1)))
    number.append(int(m.group(2)))

In [25]:
accumulator = 0
visited = np.zeros(len(data))
i = 0 # Start position

while 2 not in visited:
    visited[i]+=1
    if visited[i] == 2:
        break
    op = operation[i]
    n = number[i]
    if op == 'nop':
        i += 1
        #continue
    elif op == 'acc':
        accumulator += n
        i +=1
    elif op == 'jmp':
        i = i+n
print('Part 1: ', accumulator)

Part 1:  1489


In [26]:
#Part 2
def check_finished(operation, number):
    """Return value of accumulator if instructions manage to finish, else False"""
    accumulator = 0
    visited = np.zeros(len(data))
    i = 0
    while i > len(operation) or 2 not in visited:
        if i == len(operation):
                return accumulator
        visited[i]+=1
        if visited[i] == 2:
            return False
        op = operation[i]
        n = number[i]
        if op == 'jmp' and n == 0:
            return False
        if op == 'nop':
            i += 1
            if i > len(operation):
                return accumulator
        elif op == 'acc':
            accumulator += n
            i +=1
            if i > len(operation):
                return accumulator
        elif op == 'jmp':
            i = i+n
            if i > len(operation):
                return accumulator
#operation = ['nop', 'acc', 'jmp', 'acc', 'jmp', 'acc', 'acc', 'nop', 'acc']
#number = [0, 1, 4, 3, -3, -99, 1, -4, 6]
check_finished(operation, number)

False

In [27]:
for i, value in enumerate(operation):
    # Change nop to jmp
    if value == 'nop':
        operation[i] = 'jmp'
        if check_finished(operation, number) is not False:
            print('Part 2: ', check_finished(operation, number))
            break
        operation[i] = 'nop' # Change back
    # Change jmp to nop
    if value == 'jmp':
        operation[i] = 'nop'
        if check_finished(operation, number) is not False:
            print('Part 2: ', check_finished(operation, number))
            break
        operation[i] = 'jmp' # Change back

Part 2:  1539


# --- Day 9: Encoding Error ---

In [28]:
import numpy as np
from functools import reduce
from itertools import combinations, accumulate
xmas=np.loadtxt("data/advent_of_code_2020_day_9.txt")

In [29]:
# Part 1
n = 25  # size of preamble (n=25 i oppgave)
for i in range(n,len(xmas)+1):
    available_sums = [sum(x) for x in combinations(xmas[i-n:i], 2) if x[0] != x[1]]
    if xmas[i] in available_sums:
        continue
    else:
        print('Part 1: ', xmas[i])
        break

Part 1:  776203571.0


In [30]:
# Part 2.
# Number from Part 1: 776203571
# Hvilke sammenhengende tall i xmas summerer til dette?
part1 = 776203571  #127 in test
stop_outer_loop = False
for window_size in range(2, len(xmas)):
    n = window_size
    if stop_outer_loop:
        break
    for i in range(n,len(xmas)+1):
        available_sums = [x for x in accumulate(xmas[i-n:i])][1:]  
        # Skip the first acc in available sums, only one number
        if part1 not in available_sums:
            continue
        else:
            valid_combo = xmas[i-n:i]
            stop_outer_loop = True  #Andre måter å breake ut av ytre loop?
            break
print('Part 2: ', min(valid_combo)+max(valid_combo))

Part 2:  104800569.0


# --- Day 10: Adapter Array ---

In [31]:
import numpy as np
a=np.sort(np.loadtxt("data/advent_of_code_2020_day_10.txt"))
a = np.concatenate([[0], a, [a[-1]+3]])
a

array([  0.,   1.,   2.,   3.,   4.,   7.,   8.,   9.,  10.,  11.,  14.,
        15.,  16.,  17.,  20.,  23.,  26.,  27.,  28.,  31.,  34.,  37.,
        38.,  39.,  40.,  43.,  44.,  45.,  48.,  49.,  50.,  53.,  56.,
        57.,  58.,  59.,  60.,  63.,  64.,  65.,  66.,  69.,  70.,  71.,
        72.,  75.,  76.,  77.,  78.,  79.,  82.,  83.,  84.,  85.,  86.,
        89.,  90.,  91.,  94.,  95.,  96.,  99., 100., 101., 102., 105.,
       108., 109., 110., 111., 114., 115., 116., 119., 120., 121., 122.,
       125., 128., 131., 132., 133., 134., 137., 138., 139., 142., 145.,
       146., 149., 152., 153., 154., 155., 156., 159., 162., 163., 164.,
       165., 166., 169., 172., 175., 178., 181., 184., 185., 186., 189.])

In [32]:
b = np.concatenate([[0],a])[:-1]
b

array([  0.,   0.,   1.,   2.,   3.,   4.,   7.,   8.,   9.,  10.,  11.,
        14.,  15.,  16.,  17.,  20.,  23.,  26.,  27.,  28.,  31.,  34.,
        37.,  38.,  39.,  40.,  43.,  44.,  45.,  48.,  49.,  50.,  53.,
        56.,  57.,  58.,  59.,  60.,  63.,  64.,  65.,  66.,  69.,  70.,
        71.,  72.,  75.,  76.,  77.,  78.,  79.,  82.,  83.,  84.,  85.,
        86.,  89.,  90.,  91.,  94.,  95.,  96.,  99., 100., 101., 102.,
       105., 108., 109., 110., 111., 114., 115., 116., 119., 120., 121.,
       122., 125., 128., 131., 132., 133., 134., 137., 138., 139., 142.,
       145., 146., 149., 152., 153., 154., 155., 156., 159., 162., 163.,
       164., 165., 166., 169., 172., 175., 178., 181., 184., 185., 186.])

In [33]:
diff = a-b
diff

array([0., 1., 1., 1., 1., 3., 1., 1., 1., 1., 3., 1., 1., 1., 3., 3., 3.,
       1., 1., 3., 3., 3., 1., 1., 1., 3., 1., 1., 3., 1., 1., 3., 3., 1.,
       1., 1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 3., 1., 1., 1., 1., 3.,
       1., 1., 1., 1., 3., 1., 1., 3., 1., 1., 3., 1., 1., 1., 3., 3., 1.,
       1., 1., 3., 1., 1., 3., 1., 1., 1., 3., 3., 3., 1., 1., 1., 3., 1.,
       1., 3., 3., 1., 3., 3., 1., 1., 1., 1., 3., 3., 1., 1., 1., 1., 3.,
       3., 3., 3., 3., 3., 1., 1., 3.])

In [34]:
print("Part 1: ", (len(np.where(diff==1,)[0])) * (len(np.where(diff==3,)[0])))

Part 1:  2760


#### Part 2
(fant bare en løsning som krever for mye minne)

In [35]:
# Part 2, find the number of distinct ways to arrange the adapters
m = np.stack([a, b, diff]).T

valid_arrays1 = []
for i in range(1,len(m)-2):
    diff1 = m[i+1][0] - m[i][1]
    diff2 = m[i+2][0] - m[i][1]
    if diff1 <= 3:
        valid_arrays1.append((np.delete(m, i, 0)[:,0]))
    if diff2 <= 3:
        valid_arrays1.append((np.delete(m, i+1, 0)[:,0]))
unique_rows1 = np.unique(valid_arrays1, axis=0)
#unique_rows1

In [36]:
def create_array(a):
    b = np.concatenate([[0],a])[:-1]
    diff = a-b
    return np.stack([a, b, diff]).T

def create_new_unique_array(unique_rows):
    valid_arrays = []
    for u in unique_rows:
        m = create_array(u)
        for i in range(1,len(m)-2):
            diff1 = m[i+1][0] - m[i][1]
            diff2 = m[i+2][0] - m[i][1]
            if diff1 <= 3:
                valid_arrays.append((np.delete(m, i, 0)[:,0]))
            if diff2 <= 3:
                valid_arrays.append((np.delete(m, i+1, 0)[:,0]))
    return np.unique(valid_arrays, axis=0)

In [37]:
unique_rows = unique_rows1
print(len(unique_rows))
foo = 0
for k in range(3): # Sett høyt. Fungerer, men krever for mye minne, så fungerer ikke for Part 2
    unique_rows = create_new_unique_array(unique_rows)
    print(len(unique_rows))
    foo += len(unique_rows)
print("---")
print(1 + len(unique_rows1) + foo) 

45
990
14183
148701
---
163920


# --- Day 12: Rain Risk ---

In [38]:
import re
import numpy as np
with open("data/advent_of_code_2020_day_12.txt", "r") as fp:
    data = fp.readlines()
operations = []
numbers = []
for i, line in enumerate(data):
    m = re.match(r"([A-Z]+)(\d+)\n$", line)
    operations.append(str(m.group(1)))
    numbers.append(int(m.group(2)))

In [39]:
# Part 1
x = y = 0
direction = 90 # Initial direction towards East
for i in range(0, len(operations)):
    operation = operations[i]
    number = numbers[i]
    if operation == 'E':
        x += number
    elif operation == 'W':
        x -= number
    elif operation == 'N':
        y += number
    elif operation == 'S':
        y -= number
    elif operation == 'R':
        direction += number
    elif operation == 'L':
        direction -= number
    elif operation == 'F':
        if direction % 360 == 0: # N
            y +=  number
        elif direction % 360 == 90: #E
            x += number
        elif direction % 360 == 180: #S
            y -= number
        elif direction % 360 == 270: #W
            x -= number
print('Part 1: ', abs(x) + abs(y))

Part 1:  1010


In [40]:
# Part 2
def rotate(origin, point, angle, direction):
    """Angle in radians"""
    ox, oy = origin
    px, py = point

    if direction == "L":  #  Counter clockwise
        qx = ox + np.cos(angle) * (px - ox) - np.sin(angle) * (py - oy)
        qy = oy + np.sin(angle) * (px - ox) + np.cos(angle) * (py - oy)
    else:  # R, clockwise
        qx = ox + np.cos(angle) * (px - ox) + np.sin(angle) * (py - oy)
        qy = oy - np.sin(angle) * (px - ox) + np.cos(angle) * (py - oy)
    return qx, qy

# Testing
origin = (170,38)
point = (170+10,38+4)
angle = 90
print(rotate(origin, point, np.deg2rad(angle), "L"))
print(rotate(origin, point, np.deg2rad(angle), "R"))

(166.0, 48.0)
(174.0, 28.0)


In [41]:
x = y = 0
wx = 10  # Waypoint coordinate (relative to x)
wy = 1  # Waypoint coordinate (relative to y)
for i in range(0, len(operations)):
    operation = operations[i]
    number = numbers[i]
    if operation == 'E':
        wx += number       
    elif operation == 'W':
        wx -= number
    elif operation == 'N':
        wy += number
    elif operation == 'S':
        wy -= number
    elif operation == 'R':
        dx, dy = rotate((x, y), (x+wx, y+wy), np.deg2rad(number), "R")
        wx = dx-x
        wy = dy-y
    elif operation == 'L':
        dx, dy = rotate((x, y), (x+wx, y+wy), np.deg2rad(number), "L")
        wx = dx-x
        wy = dy-y
    elif operation == 'F':
        x += number*wx
        y += number*wy
print('Part 2: ', abs(x) + abs(y))

Part 2:  52742.0
